### ISSUE TITLE
2018年度总结和2019展望

### ISSUE THREAD

**Issue by Copyes** [Copyes/New#54]
### 背景
2018年就这么一瞬间过去了。这一年里面有着特别多的经历，18年已经过完了，现在是时候总结下自己的2018了。顺便自己的2019的期望也是要准备起来了，不光是为了2019，更是为了以后。

### 重要事件回顾
- [x] 1、准备面试，和小伙伴于某个周末在星巴克出了一份《大厂面试宝典》。
- [x] 2、三月底拿到网易的offer，同时阿里也在进行3面面试。
- [x] 3、四月原公司老板谈涨薪，但是已经心里打算去更大的平台看看了。
- [x] 4、五月入职网易，六月阿里offer下来，从网易离职去阿里了。
- [x] 5、六月二十五日入职阿里，开启新的职业生涯。
- [x] 6、九月二十日转正答辩通过，正式成为阿里人。
- [x] 7、开始了做饭生涯。

### 工作

看着上面的经历自己其实是有点难受的，一是辜负了网易老板对自己的期望，二是来了阿里发现自己就荒废了学习。但是很大一部分原因是因为平时没有时间学习，周末的时候偷懒没有动力学习了。进入19年后自己的焦虑感不知怎么回事就上来了。或许就是因为自己本身的忧患意识强，同时也是给自己压力吧。

来到阿里之后是真的体验到了加班的恐怖，还有就是老板也会给很大的压力，要技术产出，要业务输出。才来到阿里的时候是想大干一场，这也想要做一个，那也想要做一个，最后一了解什么东西都已经有人做了。
可能是自己太急于表现了，没有沉住气。

在阿里这大半年时间里面，了解到怎么整体去把控一整个项目，在把控一整个项目的时候要注意些什么。
比如项目上下游相关人员的接触沟通，业务背景和规划的了解，业务产出的整理等。这些算是软实力的提升吧，在技术上的提升感觉没有特别明显，唯一的大变化就是来了这边Vue很少写了，去写Rax weex了，输出了一个天猫这边的rax-weex的开发脚手架。感觉这些东西都是对自己本质没有什么提升的，因为没有像了解Vue一样去了解Rax(类React)，仅仅是会熟练使用的层面。对于这个很难受。

工作上整体来说就是换了新环境，积极努力的融入新环境中，在工作中快速成长起来。

### 生活

今年开始自己做饭了，因为有了宽敞的厨房，会炒大概10来个菜吧。室友在我的喂养感觉重了10斤！哈哈哈哈，其实我自己也重了几斤，再加上没有锻炼，哎，难受。希望19年控制自己的体重到120斤去吧。

哎，看着周围的人都开始谈朋友了，我和室友还是光棍，家里人也在催我找对象，每次都被我用“我也想找啊，但是找不到”的理由搪塞了。大概老爸老妈怕我成为老光棍吧。

18年还去了深圳看了灯光秀，去外伶仃岛上和朋友们一起爬到了最高峰，带着朋友年底的时候去成都玩，吃火锅了，爬了青城山。遗憾的是被港国拒绝了，没去成港国。

最后背着房贷不敢大手大脚的花钱了，希望自己提升自己能力赚更多的钱，最后买更大的house。

### 学习

上半年还有好好学习，还看了很多书，写了很多自己的代码。下班年去了阿里后，自己就感觉动力不足不想花时间去学习了。现在意识到了这个问题。希望在19年重新振作起来，好好规划自己。

### Todo List —— 2019

- [ ] 1、瘦回120斤以下，坚持锻炼。
- [ ] 2、一个月一篇精品文章写在GitHub上。
- [ ] 3、去两个没去过的城市。
- [ ] 4、一周不少于4天提交github代码（有效代码）。
- [ ] 5、看5本非技术书。
- [ ] 6、学习一门新技术。
- [ ] 7 、找个对象？？？？？？？？？

### 最后

干巴爹！！！！！

**Comment by Xaber20110202** [comment]
谈个朋友还是比较关键的，应该排在第一位
